---
- name: installation htop
  hosts: all
  tasks:
    - name: package htop
      apt:
        name: htop
        state: present
    - name: package zsh
      apt:
        name: zsh
        state: present
    - name: installation de git
      apt:
        name: git
        state: present
...