---
- name: installation
  hosts: all
  tasks:
    - name: package htop
      apt:
        name: htop
        state: present
    - name: package zsh
      apt:
        name: zsh
        state: present
    - name: installation de git
      apt:
        name: git
        state: present
    - name: Install required packages
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    - name: Docker apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Docker apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian buster stable
        state: present
    - name: Installation Docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: package pip
      apt:
        name: python-pip
        state: present
    - name: Installation modules python
      command: pip install docker
    - name: Installation modules python
      apt: 
        name: python-docker
    - name: Lancement container apache2
      docker_container:
        name: apache2
        image: httpd
        state: present
        ports:
          - "8000:80"
...